"""update user model with status

Revision ID: cc44a165ce30
Revises: 79cb8a9fa8c7
Create Date: 2025-09-29 16:36:14.825639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc44a165ce30"
down_revision: Union[str, Sequence[str], None] = "79cb8a9fa8c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("status", sa.Enum("active", "pending", name="userstatus"), nullable=True)
    )
    op.execute("UPDATE users SET status='active' WHERE status IS NULL")
    op.alter_column("users", "status", nullable=False)
    op.alter_column("users", "customer_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "customer_id", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "status")
    # ### end Alembic commands ###
