"""adding semantic field mapping model

Revision ID: 36df786243fb
Revises: 98d683d4d0e7
Create Date: 2025-12-25 14:03:07.385645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from shared.db.type_decorators import GUID

# revision identifiers, used by Alembic.
revision: str = "36df786243fb"
down_revision: Union[str, Sequence[str], None] = "98d683d4d0e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_field_mappings",
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "raw_value",
            sa.String(),
            nullable=False,
            comment="Original cell text e.g. 'Office costs'",
        ),
        sa.Column(
            "normalized_value",
            sa.String(),
            nullable=False,
            comment="Normalized form for lookup (lowercase, trimmed)",
        ),
        sa.Column(
            "mapped_to",
            sa.String(),
            nullable=False,
            comment="budget_category | budget_field | extra_field",
        ),
        sa.Column("mapped_key", sa.String(), nullable=False, comment="e.g. 'office_costs'"),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "source", sa.Enum("AI", "HUMAN", "IMPORTED", name="mappingsource"), nullable=False
        ),
        sa.Column("times_used", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False, comment="Human-confirmed mapping"),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="AI reasoning, alternatives, examples",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", GUID(), nullable=True),
        sa.Column("updated_by", GUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_semantic_field_mappings_normalized_value"),
        "semantic_field_mappings",
        ["normalized_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_semantic_field_mappings_raw_value"),
        "semantic_field_mappings",
        ["raw_value"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_semantic_field_mappings_raw_value"), table_name="semantic_field_mappings"
    )
    op.drop_index(
        op.f("ix_semantic_field_mappings_normalized_value"), table_name="semantic_field_mappings"
    )
    op.drop_table("semantic_field_mappings")
    # ### end Alembic commands ###
