"""updating template budget mapping models

Revision ID: 6393cf4425c9
Revises: eca0821c189d
Create Date: 2025-12-21 13:49:15.285144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393cf4425c9'
down_revision: Union[str, Sequence[str], None] = 'eca0821c189d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
