"""adding budget catergory and donor templates

Revision ID: 73d126ddf8ad
Revises: 5715b8d7aeda
Create Date: 2025-10-25 15:43:34.614913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from shared.db.type_decorators import GUID


# revision identifiers, used by Alembic.
revision: str = "73d126ddf8ad"
down_revision: Union[str, Sequence[str], None] = "5715b8d7aeda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "budget_categories", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "budget_categories", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("budget_categories", sa.Column("created_by", GUID(), nullable=True))
    op.add_column("budget_categories", sa.Column("updated_by", GUID(), nullable=True))
    op.add_column("budget_lines", sa.Column("category_id", GUID(), nullable=True))
    op.add_column(
        "budget_lines", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "budget_lines", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("budget_lines", sa.Column("created_by", GUID(), nullable=True))
    op.add_column("budget_lines", sa.Column("updated_by", GUID(), nullable=True))
    op.create_foreign_key(
        None, "budget_lines", "budget_categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("budgets", sa.Column("donor_template_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "budgets", "donor_templates", ["donor_template_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "budgets", type_="foreignkey")
    op.drop_column("budgets", "donor_template_id")
    op.drop_constraint(None, "budget_lines", type_="foreignkey")
    op.drop_column("budget_lines", "updated_by")
    op.drop_column("budget_lines", "created_by")
    op.drop_column("budget_lines", "updated_at")
    op.drop_column("budget_lines", "created_at")
    op.drop_column("budget_lines", "category_id")
    op.drop_column("budget_categories", "updated_by")
    op.drop_column("budget_categories", "created_by")
    op.drop_column("budget_categories", "updated_at")
    op.drop_column("budget_categories", "created_at")
    # ### end Alembic commands ###
