"""add uploaded_templates and template_budget_mappings

Revision ID: 98d683d4d0e7
Revises: 6393cf4425c9
Create Date: 2025-12-21 14:00:08.094875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from shared.db.type_decorators import GUID

# revision identifiers, used by Alembic.
revision: str = "98d683d4d0e7"
down_revision: Union[str, Sequence[str], None] = "6393cf4425c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_templates",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("owner_id", GUID(), nullable=False),
        sa.Column("funding_customer_id", GUID(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("detected_structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("uploaded", "detected", "mapped", "consumed", name="uploaded_template_status"),
            server_default=sa.text("'uploaded'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", GUID(), nullable=True),
        sa.Column("updated_by", GUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_uploaded_templates_id"), "uploaded_templates", ["id"], unique=False)
    op.create_table(
        "template_budget_mappings",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("uploaded_template_id", GUID(), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_template_id"],
            ["uploaded_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_budget_mappings_id"), "template_budget_mappings", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_template_budget_mappings_id"), table_name="template_budget_mappings")
    op.drop_table("template_budget_mappings")
    op.drop_index(op.f("ix_uploaded_templates_id"), table_name="uploaded_templates")
    op.drop_table("uploaded_templates")
    # ### end Alembic commands ###
