"""Fix budget schema

Revision ID: a24c159342ea
Revises: 63f8a0ec622c
Create Date: 2025-09-27 15:42:26.543352

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a24c159342ea"
down_revision: Union[str, Sequence[str], None] = "63f8a0ec622c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
