worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    client_max_body_size 20M;

    # Docker internal DNS resolver
    resolver 127.0.0.11 valid=30s;
    server {
        listen 80;
        

        # ---- USERS SERVICE ----
        location /api/v1/users/ {

            set $users_service "http://users:8000";
            proxy_pass $users_service/api/users/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


         # ---- AUTH SERVICE ----
        location /api/v1/auth/ {

            set $users_service "http://users:8000";
            proxy_pass $users_service/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # ---- BUDGET SERVICE ----
        location /api/v1/budgets/ {

            set $budget_service "http://budget:8000";
            proxy_pass $budget_service/api/v1/budgets/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # ---- BUDGET LINES SERVICE ----
        location /api/v1/budget-lines/ {

            set $budget_service "http://budget:8000";
            proxy_pass $budget_service/api/v1/budget-lines/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ---- API-GATEWAY ----
        location /api/v1/ {

            set $gateway_service "http://gateway:8080";
            proxy_pass $gateway_service/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ---- FRONTEND ----
        location / {

            set $frontend_service "http://frontend:80";
            proxy_pass $frontend_service/;
        }
    }
}
