docker compose up --build -d# Use node
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ['nginx', '-g', 'daemon off;']

CMD ['nginx', '-g', 'daemon off;']
